name: hassio rclone backups
version: 4
slug: berg-rclone-backup
description: "Backup Home Assistant with rclone"
url: https://github.com/berg/berg-hassio-addons
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - backup:rw
tmpfs: true
startup: once
boot: manual
options: {}
schema:
  rclone_config: "str"
  rclone_remotes: [{"definition": "str", "extra_args": "str?", "sync": "bool?"}]
  purge_days: "int?"
